name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  # numeric_keyboard: ^1.1.0
  country_icons: ^2.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/illustrations/
    - assets/vectors/icons/
    - assets/fonts/google_fonts/
